version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: docker-mysql
    networks:
      itbcode_net:
        ipv4_address: 10.3.0.11
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  php:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: docker-php
    networks:
      itbcode_net:
        ipv4_address: 10.3.0.12
    environment:
      PMA_HOST: 10.3.0.11
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHP_PORT}:80"
      - "${PM_PORT}:8080"
      - "${PHP_MY_ADMIN_PORT}:8081"
    volumes:
      - ./www:/var/www/html
      - ./etc/apache2/sites:/etc/apache2/sites
      - ./:/var/www/docker
    links:
      - mysql
networks:
  itbcode_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
